[package]
name = "bauxite-store"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yml = "0"
tokio = "1"
thiserror = "1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
